categorie : 
  type: rest
  resource:     "ApiBundle:CategorieRest"
  name_prefix:  api_
chantier : 
  type: rest
  resource:     "ApiBundle:ChantierRest"
  name_prefix:  api_
client : 
  type: rest
  resource:     "ApiBundle:ClientRest"
  name_prefix:  api_
login :
  type: rest
  resource:     "ApiBundle:CommercialRest"
  name_prefix:  api_


