<?php

namespace ApiBundle\Repository;

/**
 * ChantierProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
