<?php

namespace ApiBundle\Repository;

/**
 * EstimationProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimationProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
