<?php

namespace ApiBundle\Repository;

/**
 * IngenieurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngenieurRepository extends \Doctrine\ORM\EntityRepository
{
}
